name: CI
on:
  push:
    tags:
      - "dev-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to run
        type: environment

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
